# Generated by Django 5.2.4 on 2025-09-20 10:07

import chatting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="seen_at",
            field=models.CharField(
                default=chatting.models.get_current_datetime, max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.CharField(
                db_index=True,
                default=chatting.models.get_current_datetime,
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "receiver", "timestamp"],
                name="chatting_me_sender__bf1e12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "is_seen", "timestamp"],
                name="chatting_me_receive_415171_idx",
            ),
        ),
    ]
