# Generated by Django 5.2.4 on 2025-08-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
