# Generated by Django 5.2.4 on 2025-08-12 10:49

import chatting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0002_message_is_seen_message_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="seen_at",
            field=models.DateTimeField(default=chatting.models.get_current_datetime),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(default=chatting.models.get_current_datetime),
        ),
    ]
