# Generated by Django 5.2.4 on 2025-08-12 11:19

import chatting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0005_alter_message_seen_at_alter_message_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="seen_at",
            field=models.CharField(default=chatting.models.get_current_datetime),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.CharField(default=chatting.models.get_current_datetime),
        ),
    ]
