# Generated by Django 5.1.7 on 2025-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="course",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
