# Generated by Django 5.1.7 on 2025-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_remove_profile_course_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.CharField(
                default="https://mphkxojdifbgafp1.public.blob.vercel-storage.com/Profile/p.webp",
                max_length=255,
            ),
        ),
    ]
