# Generated by Django 5.1.7 on 2025-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="course",
            field=models.CharField(default="B.C.A", max_length=30),
        ),
    ]
