# Generated by Django 5.2.4 on 2025-09-20 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0005_profile_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["user"], name="Profile_fol_user_id_72326b_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user_obj"], name="Profile_pro_user_ob_018a9a_idx"
            ),
        ),
    ]
