# Generated by Django 5.1.6 on 2025-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_quepdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="div",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quepdf",
            name="year",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
