# Generated by Django 5.1.6 on 2025-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_quepdf_div_quepdf_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselist",
            name="number_sem",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
