# Generated by Django 5.1.6 on 2025-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_courselist_number_sem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="dateCreated",
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quepdf",
            name="name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quepdf",
            name="size",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="quepdf",
            name="timeCreated",
            field=models.TimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="pdf",
            field=models.URLField(max_length=255),
        ),
    ]
