# Generated by Django 5.1.6 on 2025-02-17 05:38

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_courselist_number_sem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="dateCreated",
            field=models.CharField(default=home.models.get_current_date, max_length=10),
        ),
        migrations.AddField(
            model_name="quepdf",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quepdf",
            name="size",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="quepdf",
            name="timeCreated",
            field=models.CharField(default=home.models.get_current_time, max_length=8),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="pdf",
            field=models.URLField(max_length=255),
        ),
    ]
