# Generated by Django 5.1.6 on 2025-02-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_quepdf_datecreated_quepdf_name_quepdf_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quepdf",
            name="size",
        ),
    ]
