# Generated by Django 5.1.6 on 2025-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_quepdf_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsPdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contant", models.TextField()),
                ("pdf", models.URLField(max_length=255)),
            ],
        ),
    ]
