# Generated by Django 5.1.6 on 2025-03-01 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_anspdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="anspdf",
            name="que_pdf",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.quepdf"
            ),
            preserve_default=False,
        ),
    ]
