# Generated by Django 5.1.6 on 2025-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_anspdf_que_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="sub",
            field=models.CharField(default="B.C.A", max_length=10),
            preserve_default=False,
        ),
    ]
