# Generated by Django 5.1.6 on 2025-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_quepdf_sub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quepdf",
            name="sub",
            field=models.CharField(max_length=100),
        ),
    ]
