# Generated by Django 5.1.6 on 2025-03-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_quepdf_sub"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sem", models.IntegerField()),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "course_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.courselist",
                    ),
                ),
            ],
        ),
    ]
