# Generated by Django 5.1.6 on 2025-03-16 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="anspdf",
            name="contant",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="pdf",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="number_sem",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="div",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="pdf",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sem",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sub",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="sem",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course", models.CharField(max_length=20, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
