# Generated by Django 5.1.6 on 2025-03-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_anspdf_contant_alter_anspdf_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user_obj",
        ),
    ]
