# Generated by Django 5.1.6 on 2025-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_user_id_profile_user_obj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anspdf",
            name="contant",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="pdf",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="number_sem",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="course",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="div",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="pdf",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sem",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sub",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="sem",
            field=models.IntegerField(),
        ),
    ]
