# Generated by Django 5.1.6 on 2025-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_anspdf_contant_alter_anspdf_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="choose",
            field=models.CharField(default="Assignment", max_length=40),
            preserve_default=False,
        ),
    ]
