# Generated by Django 5.1.6 on 2025-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_quepdf_choose"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profile",
        ),
    ]
