# Generated by Django 5.2.4 on 2025-09-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quepdf",
            name="username",
            field=models.CharField(db_index=True, default="Admin", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="pdf",
            field=models.URLField(default="Admin", max_length=255),
        ),
        migrations.AlterField(
            model_name="anspdf",
            name="que_pdf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="home.quepdf",
            ),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="choose",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="que_pdfs",
                to="home.courselist",
            ),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sem",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="sub",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quepdf",
            name="year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="home.courselist",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="sem",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="anspdf",
            index=models.Index(fields=["name"], name="home_anspdf_name_155432_idx"),
        ),
        migrations.AddIndex(
            model_name="anspdf",
            index=models.Index(
                fields=["que_pdf", "name"], name="home_anspdf_que_pdf_2d2d4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courselist",
            index=models.Index(fields=["name"], name="home_course_name_9168cb_idx"),
        ),
        migrations.AddIndex(
            model_name="quepdf",
            index=models.Index(
                fields=["course", "sem", "sub"], name="home_quepdf_course__7d4439_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quepdf",
            index=models.Index(
                fields=["username", "choose", "year"],
                name="home_quepdf_usernam_7648e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["course_obj", "sem", "name"],
                name="home_subjec_course__c667e2_idx",
            ),
        ),
    ]
