# Generated by Django 5.1.4 on 2025-01-28 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
