# Generated by Django 5.2.4 on 2025-07-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_otp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
